//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracjaSystemowProjekt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegracjaSystemowProjekt.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojemność dysku.
        /// </summary>
        internal static string DiskSizeColumnName {
            get {
                return ResourceManager.GetString("DiskSizeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj dysku.
        /// </summary>
        internal static string DiskTypeColumnName {
            get {
                return ResourceManager.GetString("DiskTypeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj napędu fizycznego w komputerze.
        /// </summary>
        internal static string DriveColumnName {
            get {
                return ResourceManager.GetString("DriveColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prędkość taktowania MHz.
        /// </summary>
        internal static string FrequencyColumnName {
            get {
                return ResourceManager.GetString("FrequencyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa układu graficznego.
        /// </summary>
        internal static string GpuColumnName {
            get {
                return ResourceManager.GetString("GpuColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy ekran jest dotykowy?.
        /// </summary>
        internal static string IsTouchableColumnName {
            get {
                return ResourceManager.GetString("IsTouchableColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa producenta.
        /// </summary>
        internal static string ManufacturerNameColumnName {
            get {
                return ResourceManager.GetString("ManufacturerNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba laptopów.
        /// </summary>
        internal static string NumberOfDevices {
            get {
                return ResourceManager.GetString("NumberOfDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba rdzeni fizycznych.
        /// </summary>
        internal static string NumberOfPhysicalCoresColumnName {
            get {
                return ResourceManager.GetString("NumberOfPhysicalCoresColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa systemu operacyjnego.
        /// </summary>
        internal static string OsColumnName {
            get {
                return ResourceManager.GetString("OsColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa procesora.
        /// </summary>
        internal static string ProcessorNameColumnName {
            get {
                return ResourceManager.GetString("ProcessorNameColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielkość pamięci RAM.
        /// </summary>
        internal static string RamColumnName {
            get {
                return ResourceManager.GetString("RamColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozdzielczość.
        /// </summary>
        internal static string ResolutionColumnName {
            get {
                return ResourceManager.GetString("ResolutionColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przekątna ekranu.
        /// </summary>
        internal static string ScreenDiagonalColumnName {
            get {
                return ResourceManager.GetString("ScreenDiagonalColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj powierzchni ekranu.
        /// </summary>
        internal static string ScreenSurfaceTypeColumnName {
            get {
                return ResourceManager.GetString("ScreenSurfaceTypeColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamięć układu graficznego.
        /// </summary>
        internal static string VramColumnName {
            get {
                return ResourceManager.GetString("VramColumnName", resourceCulture);
            }
        }
    }
}
